name: Deploy SSL Certificate

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy SSL Certificate
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          cname: lkxdy.com
          custom_domain: lkxdy.com
          custom_domain_sll_certificate: |
            -----BEGIN CERTIFICATE-----
            MIIGajCCBNKgAwIBAgIQaOgZIU7He/nmbKhu2cYTATANBgkqhkiG9w0BAQwFADBZ
            MQswCQYDVQQGEwJDTjElMCMGA1UEChMcVHJ1c3RBc2lhIFRlY2hub2xvZ2llcywg
            SW5jLjEjMCEGA1UEAxMaVHJ1c3RBc2lhIFJTQSBEViBUTFMgQ0EgRzIwHhcNMjQw
            MzAxMDAwMDAwWhcNMjUwMzA3MjM1OTU5WjAUMRIwEAYDVQQDEwlsa3hkeS5jb20w
            ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDM0CrsC+LmOydjrv5Xu5ME
            hSMpYo4Ubu2cM6nVhzhLYE7S9FDkowmjRJ+/RJC9cMgBTulxUOi3DtKocxPCXXiy
            DA5jKl5V20kA7Iqhr5R3GPQcTJb2mUgLI1g4chACW0yIf4DqJ6LJVmprZPFHI5E+
            Mqvre8Wy/XH/+Iv1Zo0JhQmLSob482CMgiorDmhfNJcRod4sJZTEukqh4dRYhf2v
            OmTCp6WWVEQFdzlpagNQvPpeDMsJwZAEkNIPh55aVUoUJkz8iudLeCNen0XBXaZf
            eibxVM3gn11c1GdLeC4iQOgS4FVYt8zfbping2C9L+sAX7KjwtCxjpjq+KniACPF
            AgMBAAGjggLxMIIC7TAfBgNVHSMEGDAWgBRfOnwREH4MZ3Fh3IujtQADZ/VXHDAd
            BgNVHQ4EFgQUw9u3gw18F+pd8FJoEEnXNu87LVwwDgYDVR0PAQH/BAQDAgWgMAwG
            A1UdEwEB/wQCMAAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMEkGA1Ud
            IARCMEAwNAYLKwYBBAGyMQECAjEwJTAjBggrBgEFBQcCARYXaHR0cHM6Ly9zZWN0
            aWdvLmNvbS9DUFMwCAYGZ4EMAQIBMH0GCCsGAQUFBwEBBHEwbzBCBggrBgEFBQcw
            AoY2aHR0cDovL2NydC50cnVzdC1wcm92aWRlci5jbi9UcnVzdEFzaWFSU0FEVlRM
            U0NBRzIuY3J0MCkGCCsGAQUFBzABhh1odHRwOi8vb2NzcC50cnVzdC1wcm92aWRl
            ci5jbjAjBgNVHREEHDAagglsa3hkeS5jb22CDXd3dy5sa3hkeS5jb20wggF9Bgor
            BgEEAdZ5AgQCBIIBbQSCAWkBZwB1AM8RVu7VLnyv84db2Wkum+kacWdKsBfsrAHS
            W3fOzDsIAAABjffNPBcAAAQDAEYwRAIgceXAyKpQFI7yTOplitcATXfC+Kx7MCuw
            9cL5hgHxfPQCIFkVHtz0mNlTTxdqubFxaT6nQ0xwc8Bpdtvo3pKvd0EqAHcAouMK
            5EXvva2bfjjtR2d3U9eCW4SU1yteGyzEuVCkR+cAAAGN9808xgAABAMASDBGAiEA
            mqNHM9ohvBDWiTbApaDWI2PCVvCCRuuvqdw2iNbXgEACIQCjRIWaGMaXY3pxblBB
            L+29fKh0U84wOstfiNvA7K4vTwB1AE51oydcmhDDOFts1N8/Uusd8OCOG41pwLH6
            ZLFimjnfAAABjffNPGMAAAQDAEYwRAIgKknUreCYUNCrnCPVnPaVekY5wNxxEZPi
            yC607EUtjNACIDbNOtCKHApYYUnhZpjIPglAqN95+E7CmhoTypomjSofMA0GCSqG
            SIb3DQEBDAUAA4IBgQBdTdaz5TyV+gi5O1WZPHwxhKa68H1eeaDNpLQsO5jX5M/J
            Pnih8EL8HKs8gglVWoaOs0OJu3xdzbDaPQJjDAAFOqgp5Rx+n1T6U+DybuFSdT1e
            nzbfawJZuw8XA2m21enp2RukNE51QCdn2G3P1Wa7IWi/y0Wssf8RVaY2WMb5M+mt
            56fDs+nbBDagaSNqb2Kid2AiCg0w/cfx22+zSmTrXqW4hMD814HxoasWNXnhgbhb
            GI6JiRlWWLL9uY/kfbwMUiudE0D+aLIDBNa55FgiVDlSZxgDDwsDZP0AXffr5BRQ
            +vV/ED7xSOxR/jENH4KKcpP5+q3v2ueZDI7y3qfGRU0IQ7fQJZY8SufVbbZFu9vJ
            9f3K6IPjGiliJ8hJ1GVXo2qGOQcUJ9NfJa6OQJxDVvGc6UTMgPnRtcqt6oCBbQ7X
            zhKkhhwlXXBEsy8ZMykudiEVT0oJqeGgzI6Ni8GQrv+ClWifXH8aAMkZHkFu9xe0
            kfOFWN8o4Mzz9oIDCD4=
            -----END CERTIFICATE-----
            -----BEGIN CERTIFICATE-----
            MIIFBzCCA++gAwIBAgIRALIM7VUuMaC/NDp1KHQ76aswDQYJKoZIhvcNAQELBQAw
            ezELMAkGA1UEBhMCR0IxGzAZBgNVBAgMEkdyZWF0ZXIgTWFuY2hlc3RlcjEQMA4G
            A1UEBwwHU2FsZm9yZDEaMBgGA1UECgwRQ29tb2RvIENBIExpbWl0ZWQxITAfBgNV
            BAMMGEFBQSBDZXJ0aWZpY2F0ZSBTZXJ2aWNlczAeFw0yMjAxMTAwMDAwMDBaFw0y
            ODEyMzEyMzU5NTlaMFkxCzAJBgNVBAYTAkNOMSUwIwYDVQQKExxUcnVzdEFzaWEg
            VGVjaG5vbG9naWVzLCBJbmMuMSMwIQYDVQQDExpUcnVzdEFzaWEgUlNBIERWIFRM
            UyBDQSBHMjCCAaIwDQYJKoZIhvcNAQEBBQADggGPADCCAYoCggGBAKjGDe0GSaBs
            Yl/VhMaTM6GhfR1TAt4mrhN8zfAMwEfLZth+N2ie5ULbW8YvSGzhqkDhGgSBlafm
            qq05oeESrIJQyz24j7icGeGyIZ/jIChOOvjt4M8EVi3O0Se7E6RAgVYcX+QWVp5c
            Sy+l7XrrtL/pDDL9Bngnq/DVfjCzm5ZYUb1PpyvYTP7trsV+yYOCNmmwQvB4yVjf
            IIpHC1OcsPBntMUGeH1Eja4D+qJYhGOxX9kpa+2wTCW06L8T6OhkpJWYn5JYiht5
            8exjAR7b8Zi3DeG9oZO5o6Qvhl3f8uGU8lK1j9jCUN/18mI/5vZJ76i+hsgdlfZB
            Rh5lmAQjD80M9TY+oD4MYUqB5XrigPfFAUwXFGehhlwCVw7y6+5kpbq/NpvM5Ba8
            SeQYUUuMA8RXpTtGlrrTPqJryfa55hTuX/ThhX4gcCVkbyujo0CYr+Uuc14IOyNY
            1fD0/qORbllbgV41wiy/2ZUWZQUodqHWkjT1CwIMbQOY5jmrSYGBwwIDAQABo4IB
            JjCCASIwHwYDVR0jBBgwFoAUoBEKIz6W8Qfs4q8p74Klf9AwpLQwHQYDVR0OBBYE
            FF86fBEQfgxncWHci6O1AANn9VccMA4GA1UdDwEB/wQEAwIBhjASBgNVHRMBAf8E
            CDAGAQH/AgEAMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAiBgNVHSAE
            GzAZMA0GCysGAQQBsjEBAgIxMAgGBmeBDAECATBDBgNVHR8EPDA6MDigNqA0hjJo
            dHRwOi8vY3JsLmNvbW9kb2NhLmNvbS9BQUFDZXJ0aWZpY2F0ZVNlcnZpY2VzLmNy
            bDA0BggrBgEFBQcBAQQoMCYwJAYIKwYBBQUHMAGGGGh0dHA6Ly9vY3NwLmNvbW9k
            b2NhLmNvbTANBgkqhkiG9w0BAQsFAAOCAQEAHMUom5cxIje2IiFU7mOCsBr2F6CY
            eU5cyfQ/Aep9kAXYUDuWsaT85721JxeXFYkf4D/cgNd9+hxT8ZeDOJrn+ysqR7NO
            2K9AdqTdIY2uZPKmvgHOkvH2gQD6jc05eSPOwdY/10IPvmpgUKaGOa/tyygL8Og4
            3tYyoHipMMnS4OiYKakDJny0XVuchIP7ZMKiP07Q3FIuSS4omzR77kmc75/6Q9dP
            v4wa90UCOn1j6r7WhMmX3eT3Gsdj3WMe9bYD0AFuqa6MDyjIeXq08mVGraXiw73s
            Zale8OMckn/BU3O/3aFNLHLfET2H2hT6Wb3nwxjpLIfXmSVcVd8A58XH0g==
            -----END CERTIFICATE-----